### ISSUE TITLE
Exclude Certain Locals Variables

### ISSUE THREAD

**Issue by Plypy** [devoidfury/express-debug#19]
How can I add some exclusion rules for the locals object.

Here's my situation, I passed `lodash` via `locals` to ease the pain. However, EDT will include all sources of `lodash` in its panel, which makes page size surprisingly large and brings some errors. So it would be great if I can exclude `lodash` from the locals panel.

Regards.

**Comment by devoidfury** [comment]
Yes, you should be able to hide lodash by setting `lodash.EDT_hidden = true` (or `_.EDT_hidden = true` if you're using the shorter name).

**Comment by Plypy** [comment]
Thanks, things are neat again.
